
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_install:
- cp .ignored.file.copy ignored.file

script:
   - nosetests -v --with-coverage --cover-package=app

after_success:
  - coveralls
